import type { Metadata } from "next";
import LegalPage from "../components/LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy — Fennrise",
  description:
    "How Fennrise collects, uses, protects, and manages personal information.",
  alternates: { canonical: "/privacy-policy" },
};

const sections = [
  {
    id: "scope",
    title: "Scope",
    content: (
      <>
        <p>
          This Privacy Policy explains how Fennrise (&quot;Fennrise&quot;,
          &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) handles personal data
          when you visit <a href="https://www.fennrise.com">www.fennrise.com</a>, join
          our waitlist, complete an optional survey, contact us, or use a related
          Fennrise website experience that links to this policy.
        </p>
        <p>
          It does not cover third-party websites or services that publish their own
          privacy terms.
        </p>
      </>
    ),
  },
  {
    id: "information",
    title: "Information we collect",
    content: (
      <>
        <p>Depending on how you interact with us, we may collect:</p>
        <ul>
          <li><strong>Waitlist details:</strong> your name, email address, and selected role.</li>
          <li><strong>Survey responses:</strong> optional product preferences and feedback.</li>
          <li><strong>Messages:</strong> information you include when you contact us.</li>
          <li><strong>Technical data:</strong> basic device, browser, IP address, request, and security logs generated by our hosting and form providers.</li>
          <li><strong>Optional analytics data:</strong> if you allow analytics, information such as pages viewed, approximate device/browser details, referral information, and interaction events used to understand website usage.</li>
        </ul>
        <p>
          Please do not send sensitive personal information through the waitlist or a
          general contact address unless it is necessary for your request.
        </p>
      </>
    ),
  },
  {
    id: "use",
    title: "How we use information",
    content: (
      <>
        <p>We use personal data only for relevant and stated purposes, including to:</p>
        <ul>
          <li>manage the Fennrise waitlist and provide launch or early-access updates;</li>
          <li>understand which products and features people find useful;</li>
          <li>reply to questions, requests, or feedback;</li>
          <li>operate, secure, troubleshoot, and improve our website; and</li>
          <li>meet legal obligations and protect our users, services, and rights.</li>
        </ul>
        <p>
          We do not sell your personal data or use waitlist information for unrelated
          advertising.
        </p>
      </>
    ),
  },
  {
    id: "consent",
    title: "Consent and your choices",
    content: (
      <>
        <p>
          When you submit the waitlist or survey form, you choose to provide the
          requested information for the purposes shown at that time. You may withdraw
          consent, request deletion, or ask us to stop sending updates at any time by
          emailing <a href="mailto:privacy@fennrise.com">privacy@fennrise.com</a>.
        </p>
        <p>
          Optional website analytics are disabled unless you choose &quot;Allow analytics&quot;.
          Choosing &quot;Essential only&quot; keeps optional analytics disabled. Your choice is
          stored locally in your browser so the website can remember it.
        </p>
        <p>
          Withdrawing consent does not affect processing already completed lawfully,
          and we may retain limited information where required for security, legal, or
          record-keeping reasons.
        </p>
      </>
    ),
  },
  {
    id: "minors-tracking",
    title: "No advertising or behavioral tracking of minors",
    content: (
      <p>
        Fennrise does not use behavioral tracking or targeted advertising based on the
        activity of any user known to be under 18. This does not affect Fennrise being
        designed for students generally; it means we do not build advertising profiles
        based on the individual activity of known young users.
      </p>
    ),
  },
  {
    id: "providers",
    title: "Service providers and sharing",
    content: (
      <>
        <p>
          We share information only when needed to operate Fennrise, follow the law,
          or protect legitimate rights. Our current website may use:
        </p>
        <ul>
          <li><strong>Vercel</strong> for website hosting and delivery;</li>
          <li><strong>Formspree</strong> to receive waitlist and survey submissions; and</li>
          <li><strong>Google Analytics</strong> for optional website analytics, loaded only after you choose to allow analytics.</li>
        </ul>
        <p>
          These providers process information under their own service terms and may
          operate infrastructure outside India. We may also disclose information when
          legally required, in a business reorganisation, or to investigate abuse or a
          security incident.
        </p>
      </>
    ),
  },
  {
    id: "retention",
    title: "Retention",
    content: (
      <p>
        We keep personal data only for as long as reasonably needed for the purposes
        described here, including managing the waitlist, communicating about launch,
        handling requests, maintaining security records, measuring website usage where
        you have allowed analytics, and meeting legal duties. We delete or anonymise
        information when it is no longer needed, subject to technical backup cycles and
        lawful retention requirements.
      </p>
    ),
  },
  {
    id: "children",
    title: "Children and young users",
    content: (
      <>
        <p>
          Fennrise is designed to support students and young professionals. If you are
          under 18, please join the waitlist only with permission from your parent or
          legal guardian.
        </p>
        <p>
          We do not knowingly process a child&apos;s personal data without the consent
          required by applicable law. A parent or guardian may contact us at
          <a href="mailto:privacy@fennrise.com"> privacy@fennrise.com</a> to review,
          correct, or request deletion of a child&apos;s information.
        </p>
      </>
    ),
  },
  {
    id: "security",
    title: "Security",
    content: (
      <p>
        We use reasonable technical and organisational measures intended to protect
        information against unauthorised access, alteration, disclosure, or loss. No
        online system is completely secure, so we cannot guarantee absolute security.
        If we become aware of a qualifying personal-data breach, we will take the
        steps required by applicable law.
      </p>
    ),
  },
  {
    id: "rights",
    title: "Your rights and grievances",
    content: (
      <>
        <p>
          Subject to applicable Indian data-protection law, you may ask for a summary
          of personal data we process, request correction or erasure, withdraw consent,
          or raise a grievance. You may also have the right to nominate another person
          to exercise certain rights where the law permits.
        </p>
        <p>
          Email <a href="mailto:privacy@fennrise.com">privacy@fennrise.com</a> with the
          subject &quot;Privacy Request&quot;. We may need to verify your identity before
          completing a request. If you are dissatisfied with our response, you may use
          the remedies available under applicable law.
        </p>
      </>
    ),
  },
  {
    id: "cookies",
    title: "Cookies and analytics",
    content: (
      <>
        <p>
          Fennrise does not use advertising cookies or targeted advertising on the
          current website. Essential hosting, security, and form functionality may use
          technical storage or logs needed to deliver the service.
        </p>
        <p>
          Google Analytics is optional. It is not loaded until you choose &quot;Allow
          analytics&quot;. If enabled, Google Analytics may use analytics cookies or similar
          identifiers to help us understand aggregate website usage. Choosing
          &quot;Essential only&quot; prevents us from loading this optional analytics integration.
        </p>
      </>
    ),
  },
  {
    id: "contact",
    title: "Changes and contact",
    content: (
      <>
        <p>
          We may update this policy as Fennrise develops. A revised version will be
          posted here with a new effective date. Material changes may also be announced
          through the website or by email where appropriate.
        </p>
        <ul>
          <li><strong>Privacy, data rights and grievances:</strong> <a href="mailto:privacy@fennrise.com">privacy@fennrise.com</a></li>
          <li><strong>General enquiries:</strong> <a href="mailto:connect@fennrise.com">connect@fennrise.com</a></li>
          <li><strong>Service support:</strong> <a href="mailto:support@fennrise.com">support@fennrise.com</a></li>
          <li><strong>Legal notices:</strong> <a href="mailto:legal@fennrise.com">legal@fennrise.com</a></li>
        </ul>
        <p>Fennrise is based in India.</p>
      </>
    ),
  },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      eyebrow="Legal · Your data"
      title="Privacy Policy"
      description="A clear explanation of what we collect, why we use it, and the choices you have."
      updated="2 September 2026"
      sections={sections}
    />
  );
}
